config/routes.rb
Rails.application.routes.draw do
  get 'purchases/new',         to: 'purchases#new',         as: 'new_purchase'
  get 'purchases/success',     to: 'purchases#success',     as: 'success'
  post 'purchases/webhook',    to: 'purchases#webhook'

  post 'cart/add',             to: 'cart#add_to_cart',      as: 'cart_add'
  delete 'cart/remove',        to: 'cart#remove_from_cart', as: 'cart_remove'
  delete 'cart/destroy/:id',   to: 'cart#destroy',          as: 'cart_destroy'

  get 'candle/new',            to: 'candle#new'
  post 'candle/create',        to: 'candle#create',         as: 'candle_create'
  get 'candle/show/:id',       to: 'candle#show',           as: 'candle_show'
  get 'candle/edit/:id',       to: 'candle#edit',           as: 'candle_edit'
  patch 'candle/update/:id',   to: 'candle#update',         as: 'candle_update'
  delete 'candle/destroy/:id', to: 'candle#destroy',        as: 'candle_destroy'

  get 'store/new',             to: 'store#new',             as: 'store_create'
  post '/stores',              to: 'store#create'
  get 'store/edit',            to: 'store#edit',            as: 'store_edit'
  patch '/store',              to: 'store#update'
  delete '/store',             to: 'store#destroy'
  get 'store/show/:id',        to: 'store#show',            as: 'store_show'
  get 'store/admin',           to: 'store#admin',           as: 'store_admin'

  # All references to home_path should have be removed however, route left just in case.
  get 'home/index',            to: 'home#index',            as: 'home'
  get 'home/profile',          to: 'home#profile',          as: 'profile'
  get 'home/edit/address',     to: 'home#edit_address',     as: 'edit_address'
  patch 'home/edit/address',   to: 'home#update_address',    as: 'address'

  root to: 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/candle.rb
class Candle < ApplicationRecord
  belongs_to :store
  after_initialize :set_initial_stock

  has_one_attached :picture
  has_many :candle_carts
  has_many :carts, through: :candle_carts
  has_many :order_items
  has_many :orders, through: :order_items

  validate :acceptable_image
  validates :name, :price, presence: true

  def set_initial_stock
    self.stock ||= 0
  end

  def acceptable_image
    return unless picture.attached?

    unless picture.byte_size <= 1.megabyte
      errors.add(:picture, "Must be 1mb or smaller")
    end

    acceptable_types = ["image/jpeg","image/jpg","image/gif", "image/png"]
    unless acceptable_types.include?(picture.content_type)
      errors.add(:picture, "Image must be a JPEG, JPG, PNG, or GIF file")
    end
  end
end

app/controllers/candle_controller.rb
class CandleController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_candle, only: [:show, :edit, :update, :destroy]

  def create
    # Create a new candle for the current users store
    parameters = candle_params
    parameters[:ingredients] = parameters[:ingredients].split
    parameters[:scents] = parameters[:scents].split
    @candle = current_user.store.candles.new(parameters)
    if @candle.save
      redirect_to store_admin_path
    else
      render :new
    end
  end

  def new
    @candle = Candle.new
  end

  def destroy
    @candle.destroy
    flash[:alert] = "Succesfully Deleted"
    redirect_to store_admin_path
  end

  def show
    # Load the correct store page for the chosen candle, and load 10 additional candles from the same store.
    @store = @candle.store
    @candles = @store.candles.sample(10)
  end

  def edit
  end

  def update
    parameters = candle_params
    # Break passed string into array of strings as expected by the model
    parameters[:ingredients] = parameters[:ingredients].split
    parameters[:scents] = parameters[:scents].split
    if @candle.update(parameters)
      redirect_to store_admin_path
    else
      # Attempting to add flash messages on failed model validation
      # flash[:form_errors] = @candle.errors.full_messages
      render :edit
    end
  end

  private

  def set_candle
    @candle = Candle.find(params[:id])
  end

  # Sanitize candle params
  def candle_params
    params.require(:candle).permit(:name, :description, :stock, :price, :scents, :ingredients, :picture)
  end
end

app/helpers/candle_helper.rb
module CandleHelper
end

app/views/candle/_form.html.erb
<ul>
  <% candle.errors.full_messages do |message| %>
    <li style='color: maroon'><%= message %></li>
  <% end %>
</ul>

<%= form_with model: candle, url: url, local: true do |form| %>
  <div class='mx-5 mb-3'>
    <div class='mb-3'>
      <%= form.label :name, class:'form-label' %>
      <%= form.text_field :name, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :description, class:'form-label' %>
      <%= form.text_area :description, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :price, class:'form-label' %>
      <%= form.number_field :price, step: 0.01, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :scents, class:'form-label' %>
      <%= form.text_field :scents, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :ingredients, class:'form-label' %>
      <%= form.text_field :ingredients, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :picture, class:'form-label' %>
      <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg, image/gif', class:'form-control' %>
    </div>
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/candle/edit.html.erb
<h1>Edit <%= @candle.name %></h1>
<p>Hints:</p>
<ul>
  <li>Scents are input as a space seperated list</li>
  <li>Ingredients are input as a space seperated list</li>
</ul>
<%= render 'form', candle: @candle, url: candle_update_path %>

app/views/candle/new.html.erb
<h1>New candle</h1>
<p>Hints:</p>
<ul>
  <li>Scents are input as a space seperated list</li>
  <li>Ingredients are input as a space seperated list</li>
</ul>
<%= render 'form', candle: @candle, url: candle_create_path %>

app/views/candle/show.html.erb
<div class="d-flex justify-content-center">
  <h1><%= @store.name %></h1>
</div>

<%= render 'shared/hero', candle: @candle %>

<div class="d-flex justify-content-between align-items-center">
  <p class="m-0"><strong><%= number_to_currency(@candle.price) %></strong> each</p>
  <div class="d-flex align-items-center">
    <%= form_with(url: cart_add_path, method: :post) do |form| %>
      <%= form.hidden_field :candle_id, value: @candle.id %>
      <%= form.label :quantity, "How many?" %>
      <%= form.number_field :quantity, in: 1..5, value: 1 %>
      <%= form.submit "Add to cart!", class:'m-2 btn btn-primary' %>
    <% end %>
  </div>
</div>


<div class="d-flex justify-content-center">
  <h2> More from <%= @store.name %>:</h2>
</div>
<%= render 'shared/searchbar' %>
<div class="card-container p-1 my-2 mx-5">
  <div class="card-group justify-content-between flex-wrap">
    <% @candles.each do |candle| %>
      <%= render 'shared/card', candle: candle%>
    <% end %>
  </div>
</div>