config/routes.rb
Rails.application.routes.draw do
  get 'purchases/new',         to: 'purchases#new',         as: 'new_purchase'
  get 'purchases/success',     to: 'purchases#success',     as: 'success'
  post 'purchases/webhook',    to: 'purchases#webhook'

  post 'cart/add',             to: 'cart#add_to_cart',      as: 'cart_add'
  delete 'cart/remove',        to: 'cart#remove_from_cart', as: 'cart_remove'
  delete 'cart/destroy/:id',   to: 'cart#destroy',          as: 'cart_destroy'

  get 'candle/new',            to: 'candle#new'
  post 'candle/create',        to: 'candle#create',         as: 'candle_create'
  get 'candle/show/:id',       to: 'candle#show',           as: 'candle_show'
  get 'candle/edit/:id',       to: 'candle#edit',           as: 'candle_edit'
  patch 'candle/update/:id',   to: 'candle#update',         as: 'candle_update'
  delete 'candle/destroy/:id', to: 'candle#destroy',        as: 'candle_destroy'

  get 'store/new',             to: 'store#new',             as: 'store_create'
  post '/stores',              to: 'store#create'
  get 'store/edit',            to: 'store#edit',            as: 'store_edit'
  patch '/store',              to: 'store#update'
  delete '/store',             to: 'store#destroy'
  get 'store/show/:id',        to: 'store#show',            as: 'store_show'
  get 'store/admin',           to: 'store#admin',           as: 'store_admin'

  # All references to home_path should have be removed however, route left just in case.
  get 'home/index',            to: 'home#index',            as: 'home'
  get 'home/profile',          to: 'home#profile',          as: 'profile'
  get 'home/edit/address',     to: 'home#edit_address',     as: 'edit_address'
  patch 'home/edit/address',   to: 'home#update_address',    as: 'address'

  root to: 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_card.html.erb
<div class="card" style="min-width:220px; max-width:250px;">
  <% if candle.picture.attached? %>
    <%= image_tag candle.picture, class: "card-img-top"%>
  <% else %>
    <%= image_tag 'https://via.placeholder.com/1600x900?text=No+Image+Available', class: "card-img-top", style: "width:100%"%>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= candle.name %></h5>
    <p class="card-text"><%= candle.description %></p>
    <div class="card-footer">
      <%= link_to "See More", candle_show_path(candle.id), class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_card_order.html.erb
<div class="card" style="min-width:220px; max-width:250px;">
  <div class="card-body">
    <h4 class="card-title text-center">
      <%= info[:store_name] %>
    </h4>
    <p class="card-text text-center">
      <%= info[:created_at].strftime('%d-%m-%Y') %>
    </p>
    <p class="card-text text-center">
      <strong><%= number_to_currency(info[:total_price]) %></strong>
    </p>
    <div class="card-footer d-flex justify-content-center">
      <%= link_to "View Receipt", info[:receipt_url], class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_cart.html.erb
<p>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Show Cart
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <ul class="list-group">
      <%# Cart needs to be specified across all views, and thus cannot be passed a query through a single controller %>
      <% current_user.cart.candle_carts.each do |item| %>
        <div>
          <% if item.cart.status == 'shopping' %>
            <%= link_to "Remove", cart_remove_path(id: item), method: :delete, class: "m-1 btn btn-outline-danger btn-sm"%>
          <% else %>
            <%= link_to "Remove", cart_remove_path(id: item), method: :delete, class: "m-1 btn btn-outline-danger btn-sm disabled"%>
          <% end %>
          <%= link_to(
            "#{item.quantity}x #{item.candle.name} for #{number_to_currency(item.candle.price)} each. Totalling: #{number_to_currency(item.candle.price*item.quantity)}", 
            candle_show_path(item.candle.id), 
            class: "btn"
            )%>
        </div>
      <% end %>
    </ul>

    <%# Cart needs to be specified across all views, and thus cannot be passed a query through a single controller %>
    <% case current_user.cart.status %>
    <% when 'shopping' %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to 'Proceed to Checkout', new_purchase_path, class:'m-1 btn btn-outline-primary' %>
        <%= link_to 'Delete Cart', cart_destroy_path(current_user.id), method: :delete, data:{ confirm: 'Are you sure?'}, class:'m-1 btn btn-outline-danger' %>
      </div>
    <% when 'pending' %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <p>Transaction pending, please wait</p>
        <%= link_to 'Proceed to Checkout', new_purchase_path, class:'m-1 btn btn-outline-primary disabled' %>
        <%= link_to 'Delete Cart', cart_destroy_path(current_user.id), method: :delete, data:{ confirm: 'Are you sure?'}, class:'m-1 btn btn-outline-danger disabled' %>
      </div>
    <% when 'complete' %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <p>Transaction completed successfullt</p>
      </div>
    <% end %>
    
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer border-top mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Oil in Wax | Copywrite 2021</span>
  </div>
</footer>

app/views/shared/_hero.html.erb
<div class="bg-secondary text-white rounded-3">
  <div class="container-fluid px-5" >
    <% if local_assigns.has_key? :candle %>
      <h1 class="display-4 fw-bold text-center"><%= candle.name %></h1>
    <% else %>
      <h1 class="display-4 fw-bold text-center">Oil in Wax</h1>
    <% end %>
    <div class="container-fluid p-2 d-flex justify-content-center">
      <% if local_assigns.has_key? :candle %>
        <% if candle.picture.attached? %>
          <%= image_tag candle.picture, class: "splash-image"%>
        <% else %>
          <%= image_tag 'https://via.placeholder.com/1600x900?text=No+Image+Available', class: "splash-image"%>
        <% end %>
      <% else %>
        <%= image_tag 'candle_backdrop', class: "splash-image"%>
      <% end %>
    </div>
    <div class="container-fluid p-2">
      <% if local_assigns.has_key? :candle %>
        <p class=" fs-5 text-center"><%= candle.description %></p>
        <p class=" fs-6 text-center"><strong>Scents: </strong>
          <% candle.scents.each do |scent| %>
            <%= "#{scent.capitalize}, " %>
          <% end %>
        </p>
        <p class=" fs-6 text-center"><strong>Ingredients: </strong>
          <% candle.ingredients.each do |ingredient| %>
            <%= "#{ingredient.capitalize}, " %>
          <% end %>
        </p>
      <% else %>
        <p class=" fs-5 text-center">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <%= link_to root_path, class:"navbar-brand" do %>
      <%= image_tag "logo-placeholder.png", style: "max-height: 30px;" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <% if current_user.store %>
              <%= link_to "Store", store_admin_path, class:"nav-link" %>
            <% else %>
              <%= link_to "Open Store", store_create_path, class:"nav-link" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item"><div class="mx-1 btn btn-dark disabled"><%= current_user.username %></div></li>
            <li class="nav-item">
              <%= link_to "Sign-out", destroy_user_session_path, method: :delete, class: "mx-1 btn btn-danger" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign-Up", new_user_registration_path, class: "mx-1 btn btn-primary" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign-In", user_session_path, class: "mx-1 btn btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_searchbar.html.erb
<div class="p-1 my-2 mx-5 bg-secondary text-white rounded-3">
  <%= form_tag root_path, method: :get, class: "d-flex justify-content-evenly" do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search - Not Yet Implemented", class: "form-control"%>
      <%= submit_tag "Search", class: "btn btn-primary disabled" %>
  <% end %>
</div>