config/routes.rb
Rails.application.routes.draw do
  get 'purchases/new',         to: 'purchases#new',         as: 'new_purchase'
  get 'purchases/success',     to: 'purchases#success',     as: 'success'
  post 'purchases/webhook',    to: 'purchases#webhook'

  post 'cart/add',             to: 'cart#add_to_cart',      as: 'cart_add'
  delete 'cart/remove',        to: 'cart#remove_from_cart', as: 'cart_remove'
  delete 'cart/destroy/:id',   to: 'cart#destroy',          as: 'cart_destroy'

  get 'candle/new',            to: 'candle#new'
  post 'candle/create',        to: 'candle#create',         as: 'candle_create'
  get 'candle/show/:id',       to: 'candle#show',           as: 'candle_show'
  get 'candle/edit/:id',       to: 'candle#edit',           as: 'candle_edit'
  patch 'candle/update/:id',   to: 'candle#update',         as: 'candle_update'
  delete 'candle/destroy/:id', to: 'candle#destroy',        as: 'candle_destroy'

  get 'store/new',             to: 'store#new',             as: 'store_create'
  post '/stores',              to: 'store#create'
  get 'store/edit',            to: 'store#edit',            as: 'store_edit'
  patch '/store',              to: 'store#update'
  delete '/store',             to: 'store#destroy'
  get 'store/show/:id',        to: 'store#show',            as: 'store_show'
  get 'store/admin',           to: 'store#admin',           as: 'store_admin'

  # All references to home_path should have be removed however, route left just in case.
  get 'home/index',            to: 'home#index',            as: 'home'
  get 'home/profile',          to: 'home#profile',          as: 'profile'
  get 'home/edit/address',     to: 'home#edit_address',     as: 'edit_address'
  patch 'home/edit/address',   to: 'home#update_address',    as: 'address'

  root to: 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :edit_address, :update_address]
  before_action :set_user
  before_action :set_address, only: [:profile, :edit_address, :update_address]
  def index
    @candles = Candle.all.sample(10)
  end

  def profile
    # Include related candles and stores in query to eager load necessary data 
    # for rendering cards
    @orders = @user.orders.includes(:order_items).includes(:candles, :stores)
  end

  def edit_address
  end

  def update_address
    if @address.update(address_params)
      redirect_to profile_path
    else
      # Attempting to add flash messages on failed model validation
      # Below method does not seem to work
      # flash[:form_errors] = @address.errors.full_messages
      render :edit_address
    end
  end

  protected

  def set_user
    @user = current_user
  end

  def set_address
    @address = @user.address
  end

  def address_params
    params.require(:address).permit(:state, :city, :street, :street_num, :post_code)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_profile.html.erb
<div class="bg-secondary text-white rounded-3">
  <div class="container-fluid p-5" >
    <h1 class="display-4 fw-bold text-center"><%= @user.username %></h1>

    <div class="row row-cols-4 py-4">
      <div class="col">
      </div>
      <div class="col">
        <p class=" fs-5 my-0 text-start"><strong>Email Address: </strong></p>
      </div>
      <div class="col">
        <p class=" fs-5 my-0 text-start">
          <%= @user.email %> 
      </div>
      <div class="col">
      </div>
    </div>

    <div class="row row-cols-4 py-4">
      <div class="col">
      </div>
      <div class="col">
        <p class=" fs-5 my-0 text-start"><strong>Shipping Address: </strong></p>
      </div>
      <div class="col">
        <p class=" fs-5 my-0 text-start">
          <%= @address.street_num %> 
          <%= @address.street %>
        </p>
        <p class=" fs-5 my-0 text-start">
          <%= @address.city %> 
          <%= @address.state %>, 
          <%= @address.post_code %>
        </p>
      </div>
      <div class="col">
      </div>
    </div>

    <div class="d-grid gap-2 d-md-flex-col justify-content-md-center">
      <%= link_to 'Update Address', edit_address_path, class:'m-2 btn btn-outline-light' %>
      <%= link_to 'Update Email or Password', edit_user_registration_path, class:'m-2 btn btn-outline-light' %>
    </div>
  </div>
</div>

app/views/home/edit_address.html.erb
<h1>Edit Address</h1>

<ul>
  <% @address.errors.full_messages do |message| %>
    <li style='color: maroon'><%= message %></li>
  <% end %>
</ul>

<%= form_with model: @address, url: address_path , local: true do |form| %>
  <div class='mx-5 mb-3'>
    <div class='mb-3'>
      <%= form.label :street_num, "Street Number", class:'form-label' %>
      <%= form.number_field :street_num, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :street, class:'form-label' %>
      <%= form.text_field :street, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :city, class:'form-label' %>
      <%= form.text_field :city, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :state, class:'form-label' %>
      <%= form.text_field :state, class:'form-control' %>
    </div>
    <div class='mb-3'>
      <%= form.label :post_code, class:'form-label' %>
      <%= form.number_field :post_code, class:'form-control' %>
    </div>
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render 'shared/hero' %>

<%= render 'shared/searchbar' %>

<div class="card-container p-1 my-2 mx-5">
  <div class="card-group justify-content-between flex-wrap">
    <% @candles.each do |candle| %>
      <%= render 'shared/card', candle: candle%>
    <% end %>
  </div>
</div>

app/views/home/profile.html.erb
<%= render 'profile', locals: {user: @user, address: @address} %>

<div class="d-flex justify-content-center">
  <h2>Past Orders:</h2>
</div>
<%= render 'shared/searchbar' %>
<div class="card-container p-1 my-2 mx-5">
  <div class="card-group justify-content-around flex-wrap">
    <% @orders.each do |order| %>
      <%= render 'shared/card_order', info: order.order_info%>
    <% end %>
  </div>
</div>