config/routes.rb
Rails.application.routes.draw do
  get 'purchases/new',         to: 'purchases#new',         as: 'new_purchase'
  get 'purchases/success',     to: 'purchases#success',     as: 'success'
  post 'purchases/webhook',    to: 'purchases#webhook'

  post 'cart/add',             to: 'cart#add_to_cart',      as: 'cart_add'
  delete 'cart/remove',        to: 'cart#remove_from_cart', as: 'cart_remove'
  delete 'cart/destroy/:id',   to: 'cart#destroy',          as: 'cart_destroy'

  get 'candle/new',            to: 'candle#new'
  post 'candle/create',        to: 'candle#create',         as: 'candle_create'
  get 'candle/show/:id',       to: 'candle#show',           as: 'candle_show'
  get 'candle/edit/:id',       to: 'candle#edit',           as: 'candle_edit'
  patch 'candle/update/:id',   to: 'candle#update',         as: 'candle_update'
  delete 'candle/destroy/:id', to: 'candle#destroy',        as: 'candle_destroy'

  get 'store/new',             to: 'store#new',             as: 'store_create'
  post '/stores',              to: 'store#create'
  get 'store/edit',            to: 'store#edit',            as: 'store_edit'
  patch '/store',              to: 'store#update'
  delete '/store',             to: 'store#destroy'
  get 'store/show/:id',        to: 'store#show',            as: 'store_show'
  get 'store/admin',           to: 'store#admin',           as: 'store_admin'

  # All references to home_path should have be removed however, route left just in case.
  get 'home/index',            to: 'home#index',            as: 'home'
  get 'home/profile',          to: 'home#profile',          as: 'profile'
  get 'home/edit/address',     to: 'home#edit_address',     as: 'edit_address'
  patch 'home/edit/address',   to: 'home#update_address',    as: 'address'

  root to: 'home#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :candles, dependent: :destroy
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :authenticate_user!, only: [:new, :admin, :edit, :update, :destroy]
  before_action :set_store, only: [:admin, :edit, :update, :destroy]

  # Create new store for user
  def new
    @store = Store.new
  end

  def show
    @store = Store.find(params[:id])
    @candles = @store.candles
  end

  # Index View for store administration
  def admin
    @candles = @store.candles
  end

  def index
  end
  
  # Create new store for user 
  def create
    @store = current_user.build_store(store_params)
    if @store.save
      redirect_to store_admin_path
    else
      render :new
    end
  end

  # Admin only, edit store name 
  def edit
  end
  
  # Admin only, update store name 
  def update
    if @store.update(store_params)
      redirect_to store_admin_path
    else
      render :edit
    end
  end
  
  # Admin only, delete store name 
  def destroy
    @store.destroy
    flash[:alert] = "Succesfully Destroyed"
    redirect_to root_path
  end

  private

  def set_store
    @store = current_user.store
  end

  # Sanitize new store parameters
  def store_params
    params.require(:store).permit(:name)
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_form.html.erb
<%= form_with model: store, local: true do |form| %>
  <div class='mb-3'>
    <%= form.label :name, class:'form-label' %>
    <%= form.text_field :name, class:'form-control' %>
  </div>
  <%= form.submit class:'btn btn-primary'%>
<% end %>

app/views/store/_stock-card.html.erb
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4 d-flex flex-column">
      <% if candle.picture.attached? %>
        <%= image_tag candle.picture, class: "card-img-top"%>
      <% else %>
        <%= image_tag 'https://via.placeholder.com/1600x900?text=No+Image+Available', class: "card-img-left"%>
      <% end %>
      <%= link_to 'Edit', candle_edit_path(candle.id), class:'m-1 btn btn-primary' %>
      <%= link_to 'Deactivate Listing', root_path, class:'m-1 btn btn-primary disabled' %>
      <% if candle.stock <= 0 %>
        <%= link_to 'Delete Listing', candle_destroy_path(candle.id), method: :delete, data:{ confirm: 'Are you sure?'}, class:'m-1 btn btn-danger' %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><strong>Name: </strong><%= candle.name %></h5>
        <p class="card-text"><strong>Description: </strong><%= candle.description %></p>
        <p class="card-text">
          <small class="text-muted"><strong>Scents: </strong>
            <% candle.scents.each do |i| %>
              <%= "#{i}," %>
            <% end %>
          </small>
        </p>
        <p class="card-text">
          <small class="text-muted"><strong>Ingredients: </strong>
            <% candle.ingredients.each do |i| %>
              <%= "#{i}," %>
            <% end %>
          </small>
        </p>
        <span class="card-text badge bg-primary"><%= number_to_currency(candle.price) %></span>
        <span class="card-text badge bg-secondary "><%= candle.stock %> Ordered</span>
      </div>
    </div>
  </div>
</div>

app/views/store/admin.html.erb
<h1><%= @store.name %> Administration</h1>
<%= link_to 'Rename Store', store_edit_path, class:'btn btn-primary' %>
<%= link_to 'Close Store', store_path, method: :delete, data:{ confirm: 'Are you sure?'}, class:'btn btn-danger disabled' %>

<h2>Active stock</h2>

<% @candles.each do |candle| %>
  <%= render 'stock-card', candle: candle %>
<% end %>

<%= link_to 'Create a Listing', candle_new_path, class:'btn btn-primary' %>

app/views/store/edit.html.erb
<h1>Update <%= @store.name %>!</h1>
<p>Input a new store name:</p>

<%= render 'form', store: @store %>

app/views/store/new.html.erb
<h1>Create your store!</h1>
<p>Creating a store is easy, all you need is a name:</p>

<%= render 'form', store: @store %>

app/views/store/show.html.erb
<h1>Store View Not yet implemented</h1>